import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { createProjectMemoryRecord, currentTimestamp, getDatabaseSnapshot, mutateDatabase, updateWorkSessionTimestamp } from "@/lib/server/db/file-db";
import { emitEvent } from "@/lib/server/events";
import { boundedText } from "@/lib/server/text-bounds";
import type {
  AgentRunRecord,
  Identifier,
  ProjectMemoryCategory,
  ProjectMemoryRecord,
  ProjectMemoryScope,
  ProjectMemorySourceKind,
  ProjectMemoryStatus,
  RuntimeKind,
  TranscriptTurnRecord,
  WorkSessionRecord,
} from "@/lib/shared/types";

const maxPromptMemories = 14;
const maxExtractedMemoriesPerRun = 8;

function normalizeMemoryText(input: string): string {
  return input.replace(/\s+/g, " ").trim();
}

function memoryKey(input: string): string {
  return normalizeMemoryText(input).toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
}

function categoryFor(content: string): ProjectMemoryCategory {
  const lower = content.toLowerCase();
  if (/(verify|test|lint|typecheck|preview|render|failure|failed|error)/.test(lower)) return "verification";
  if (/(style|ui|layout|visual|design|responsive|color|font|animation)/.test(lower)) return "style";
  if (/(must|never|avoid|preserve|constraint|require|only|do not)/.test(lower)) return "constraint";
  if (/(architecture|adapter|route|api|state|database|schema|provider|runtime)/.test(lower)) return "architecture";
  if (/(handoff|continue|provider|codex|claude|agy|ollama)/.test(lower)) return "handoff";
  return "decision";
}

function looksDurable(content: string): boolean {
  const lower = content.toLowerCase();
  if (content.length < 32 || content.length > 700) return false;
  if (/^(ok|done|completed|finished|i made|i have|here are|summary:)/i.test(content)) return false;
  return /(uses?|built|implemented|configured|preserve|avoid|must|should|keep|requires?|decision|architecture|style|verification|provider|runtime|workspace|app|project|fix(?:ed)?|changed)/.test(lower);
}

function candidateSentences(input: string): string[] {
  return input
    .replace(/\r/g, "")
    .split(/(?:\n+|(?<=[.!?])\s+)/)
    .map((sentence) => normalizeMemoryText(sentence.replace(/^[-*]\s*/, "")))
    .filter(looksDurable)
    .map((sentence) => boundedText(sentence, 360));
}

function sourceLabel(memory: ProjectMemoryRecord): string {
  const provider = memory.sourceProvider === null ? "" : `, ${memory.sourceProvider}`;
  return `${memory.sourceKind}${provider}`;
}

async function mirrorProjectMemoryFile(workSession: WorkSessionRecord, memories: ProjectMemoryRecord[]): Promise<void> {
  const active = memories
    .filter((memory) => memory.status === "active" && (memory.workSessionId === null || memory.workSessionId === workSession.id || memory.scope !== "session"))
    .sort((a, b) => Number(b.pinned) - Number(a.pinned) || new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime());
  const targetDir = path.join(workSession.activeWorktreePath, ".orchestrator");
  await mkdir(targetDir, { recursive: true });
  const content = [
    "# Project Memory",
    "",
    "This file is generated by the orchestration app. The database is the source of truth.",
    "",
    ...active.map((memory) => `- [${memory.category}${memory.pinned ? ", pinned" : ""}] ${memory.content}`),
    "",
  ].join("\n");
  await writeFile(path.join(targetDir, "project-memory.md"), content, "utf8");
}

export async function renderProjectMemoryPromptBlock(workSessionId: Identifier, options: { forceInclude?: boolean } = {}): Promise<string> {
  const db = await getDatabaseSnapshot();
  const workSession = db.workSessions.find((candidate) => candidate.id === workSessionId);
  if (workSession === undefined) return "";
  const projectMemories = db.projectMemories
    .filter((memory) =>
      memory.projectId === workSession.projectId &&
      memory.status === "active" &&
      (memory.scope !== "session" || memory.workSessionId === workSession.id)
    )
    .sort((a, b) => Number(b.pinned) - Number(a.pinned) || new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime())
    .slice(0, maxPromptMemories);
  if (projectMemories.length === 0 && options.forceInclude !== true) return "";
  const now = currentTimestamp();
  const ids = new Set(projectMemories.map((memory) => memory.id));
  if (ids.size > 0) {
    await mutateDatabase((mutable) => {
      for (const memory of mutable.projectMemories) {
        if (ids.has(memory.id)) memory.lastInjectedAt = now;
      }
    });
  }
  return [
    "Trusted project memory:",
    "These durable project-specific facts are maintained by the orchestration app. Apply them unless the current user request explicitly supersedes them.",
    ...projectMemories.map((memory) => `- [${memory.category}] ${memory.content}`),
  ].join("\n");
}

export async function listProjectMemories(workSessionId: Identifier): Promise<ProjectMemoryRecord[]> {
  const db = await getDatabaseSnapshot();
  const workSession = db.workSessions.find((candidate) => candidate.id === workSessionId);
  if (workSession === undefined) return [];
  return db.projectMemories
    .filter((memory) => memory.projectId === workSession.projectId && (memory.scope !== "session" || memory.workSessionId === workSession.id))
    .sort((a, b) => Number(b.pinned) - Number(a.pinned) || new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime());
}

export async function createManualProjectMemory(input: {
  workSessionId: Identifier;
  content: string;
  category?: ProjectMemoryCategory;
  scope?: ProjectMemoryScope;
  status?: ProjectMemoryStatus;
  pinned?: boolean;
}): Promise<ProjectMemoryRecord> {
  const content = normalizeMemoryText(input.content);
  if (content.length < 3) throw new Error("Project memory content is required.");
  const record = await mutateDatabase((db) => {
    const workSession = db.workSessions.find((candidate) => candidate.id === input.workSessionId);
    if (workSession === undefined) throw new Error("Work session was not found.");
    const existing = new Set(db.projectMemories.filter((memory) => memory.projectId === workSession.projectId).map((memory) => memoryKey(memory.content)));
    if (existing.has(memoryKey(content))) throw new Error("A matching project memory already exists.");
    const memory = createProjectMemoryRecord({
      projectId: workSession.projectId,
      workSessionId: input.scope === "session" ? workSession.id : null,
      scope: input.scope ?? "project",
      category: input.category ?? categoryFor(content),
      content,
      sourceKind: "user",
      sourceId: null,
      sourceProvider: null,
      confidence: 1,
      status: input.status ?? "active",
      pinned: input.pinned ?? false,
    });
    db.projectMemories.push(memory);
    updateWorkSessionTimestamp(workSession);
    return memory;
  });
  await afterProjectMemoryChanged(input.workSessionId, "created");
  return record;
}

export async function updateProjectMemory(input: {
  workSessionId: Identifier;
  memoryId: Identifier;
  content?: string;
  category?: ProjectMemoryCategory;
  scope?: ProjectMemoryScope;
  status?: ProjectMemoryStatus;
  pinned?: boolean;
}): Promise<ProjectMemoryRecord> {
  const updated = await mutateDatabase((db) => {
    const workSession = db.workSessions.find((candidate) => candidate.id === input.workSessionId);
    if (workSession === undefined) throw new Error("Work session was not found.");
    const memory = db.projectMemories.find((candidate) => candidate.id === input.memoryId && candidate.projectId === workSession.projectId);
    if (memory === undefined) throw new Error("Project memory was not found.");
    if (input.content !== undefined) memory.content = normalizeMemoryText(input.content);
    if (input.category !== undefined) memory.category = input.category;
    if (input.scope !== undefined) {
      memory.scope = input.scope;
      memory.workSessionId = input.scope === "session" ? workSession.id : null;
    }
    if (input.status !== undefined) memory.status = input.status;
    if (input.pinned !== undefined) memory.pinned = input.pinned;
    memory.updatedAt = currentTimestamp();
    updateWorkSessionTimestamp(workSession);
    return { ...memory };
  });
  await afterProjectMemoryChanged(input.workSessionId, "updated");
  return updated;
}

export async function deleteProjectMemory(workSessionId: Identifier, memoryId: Identifier): Promise<void> {
  await mutateDatabase((db) => {
    const workSession = db.workSessions.find((candidate) => candidate.id === workSessionId);
    if (workSession === undefined) throw new Error("Work session was not found.");
    db.projectMemories = db.projectMemories.filter((memory) => !(memory.id === memoryId && memory.projectId === workSession.projectId));
    updateWorkSessionTimestamp(workSession);
  });
  await afterProjectMemoryChanged(workSessionId, "deleted");
}

async function afterProjectMemoryChanged(workSessionId: Identifier, action: string): Promise<void> {
  const db = await getDatabaseSnapshot();
  const workSession = db.workSessions.find((candidate) => candidate.id === workSessionId);
  if (workSession !== undefined) {
    await mirrorProjectMemoryFile(workSession, db.projectMemories.filter((memory) => memory.projectId === workSession.projectId)).catch(() => undefined);
  }
  await emitEvent({
    workSessionId,
    eventName: "project.memory.changed",
    aggregateType: "project_memory",
    aggregateId: null,
    payload: { action },
    producer: { module: "project-memory" },
    context: {},
  });
}

export async function extractProjectMemoryFromRun(input: {
  workSessionId: Identifier;
  agentRun: AgentRunRecord;
  summary: string;
  transcript: TranscriptTurnRecord[];
}): Promise<ProjectMemoryRecord[]> {
  const snippets = [
    ...candidateSentences(input.summary),
    ...input.transcript.flatMap((turn) => candidateSentences(turn.finalText)),
  ].slice(0, maxExtractedMemoriesPerRun);
  if (snippets.length === 0) return [];
  const created = await mutateDatabase((db) => {
    const workSession = db.workSessions.find((candidate) => candidate.id === input.workSessionId);
    if (workSession === undefined) return [];
    const existing = new Set(db.projectMemories.filter((memory) => memory.projectId === workSession.projectId).map((memory) => memoryKey(memory.content)));
    const records: ProjectMemoryRecord[] = [];
    for (const snippet of snippets) {
      const key = memoryKey(snippet);
      if (existing.has(key)) continue;
      existing.add(key);
      const sourceKind: ProjectMemorySourceKind = input.transcript.some((turn) => turn.finalText.includes(snippet)) ? "transcript" : "agent_run";
      const memory = createProjectMemoryRecord({
        projectId: workSession.projectId,
        workSessionId: null,
        scope: "project",
        category: categoryFor(snippet),
        content: snippet,
        sourceKind,
        sourceId: input.agentRun.id,
        sourceProvider: input.agentRun.runtimeKind as RuntimeKind,
        confidence: 0.68,
        status: "candidate",
        pinned: false,
      });
      db.projectMemories.push(memory);
      records.push(memory);
    }
    if (records.length > 0) updateWorkSessionTimestamp(workSession);
    return records;
  });
  if (created.length > 0) {
    await afterProjectMemoryChanged(input.workSessionId, `extracted:${created.length}`);
  }
  return created;
}

export function summarizeProjectMemory(memory: ProjectMemoryRecord): string {
  return `[${memory.status}${memory.pinned ? ", pinned" : ""}; ${sourceLabel(memory)}] ${memory.content}`;
}
