import { getConfig } from "@/lib/server/config";

export function mlMethodologyGuidance(): string {
  const config = getConfig();
  if (!config.mlPipelineEnabled) {
    return "";
  }
  return [
    "",
    "Machine-learning task shaping (python-ml stack only):",
    "- The orchestrator runs experiments, not the agent. The agent writes code that: reads .orchestrator/experiment/run_config.json (path also in EXPERIMENT_CONFIG); accepts a --smoke flag; writes metrics.jsonl (one JSON object per line, streamed incrementally -- see the live-preview note below) plus a final metrics.json. Do NOT create or overwrite experiment.json -- it is the orchestrator's run manifest; write any run/config metadata to metrics.json or another file (e.g. run_summary.json).",
    "- CRITICAL -- ONE runnable entrypoint, at the manifest path. The orchestrator executes exactly the manifest entrypoint at the workspace ROOT (the scaffolded train.py / finetune.py / etc.) as `python <entrypoint> --smoke` and `python <entrypoint>` (no other arguments), plus predict.py for inference. So: `python <entrypoint> --smoke` and `python <entrypoint>` MUST work as-is; do NOT add required positional args or flags like --config/--data_dir/--out_dir (the orchestrator never passes them, and reads run_config.json instead); and do NOT build a separate training CLI in a subdirectory (e.g. scripts/train.py) -- the orchestrator will not find or run it, so your real model would never train. Put model/library code in any modules or packages you like (root or subfolders) and import them from the root entrypoint, but the trainer entrypoint and predict.py MUST remain the exact files the orchestrator scaffolded. If you outgrow the scaffolded entrypoint, KEEP its filename and make it the real trainer rather than introducing a new CLI.",
    "- CRITICAL -- ALL data preparation is internal and happens at run time, inside the entrypoint. Read the raw dataset role paths from run_config (or your built-in data) and tokenize / encode / split / pack entirely within the run. Do NOT require a separate preparation command, a manual step, or pre-built artifacts (tokenized .bin/.npz shards, a prebuilt tokenizer, a cached dataset) that the orchestrator does not generate -- it ONLY runs the entrypoint, so anything a prep step would have produced must instead be produced on the fly by the entrypoint. Given a single corpus, make any train/val/test split internally; build vocab/tokenizer on the fly (you MAY cache it under the workspace during the run, but never DEPEND on a cache existing beforehand). The user supplies at most a raw corpus; everything else is the entrypoint's job.",
    "- Live training preview (metrics.jsonl MUST stream): the orchestrator polls metrics.jsonl ~every 1.5s during a run and feeds each NEW line to the live training chart. So APPEND one JSON object the moment each metric is computed and FLUSH (open in append mode, e.g. a small `append_metric(path, row)` helper), and truncate the file ONCE at the start of a full run. Do NOT accumulate all rows in memory and write the file once at the end -- that is the single most common cause of a chart that stays blank until the run finishes. (The --smoke gate does not need metrics.jsonl.) Each row is a flat object like {\"t\": seconds, \"step\": int, \"split\": \"train\"|\"val\"|\"test\", \"name\": str, \"value\": float} (add \"depth\" for per-recursion metrics); emit train-loss rows periodically during the loop AND eval-quality rows (accuracy/exact_match/f1/etc. on a held-out val split) at each checkpoint -- stream BOTH live, not just loss, so the user can watch accuracy climb during training rather than only seeing it at the end. The chart gives accuracy-family metrics their own [0,1] axis, so a streamed val-accuracy curve reads clearly alongside loss.",
    "- run_config.json keys: every numeric knob is provided at top level in BOTH conventions, so read whichever you prefer: max_steps/maxSteps, gradient_accumulation_steps/gradAccum, learning_rate/lr, num_epochs/epochs, subset_limit/subsetLimit, per_device_train_batch_size/batchSize; model-architecture knobs (when the operator sets them) appear the same way: block_size/blockSize (also context_length), embed_dim/embedDim (also embedding_dim), hidden_dim/hiddenDim, num_layers/numLayers (also layers); decode settings appear flat (max_new_tokens, temperature, top_p) as well as nested under decode. Any operator-supplied custom knob (e.g. eval_steps, max_length) is passed through verbatim at top level. Honor these so the run is controllable; fall back to a sensible default when a key is absent/null. extra values arrive as strings, so coerce them.",
    "- Dataset & training mode (general contract): the operator declares the run's regime and data locations in run_config; honor them. Read dataset_mode (builtin | single_corpus | train_test | train_val_test | jsonl_finetune | custom) and dataset_format (auto | text | jsonl | csv | image_folder | other), plus the workspace-relative role paths train_path/val_path/test_path/corpus_path (each may be absent/null). Load training data from train_path (or corpus_path) and the held-out eval set from test_path (val_path for early stopping); if only one is given, split internally; if mode==builtin or no paths, use your built-in/default data. The orchestrator is modality-agnostic and only assigns locations to roles -- YOU implement the loader for your modality/format: text -> read/concatenate files; jsonl_finetune -> parse prompt/completion or messages records; csv -> columns (e.g. a SMILES column for molecules); image_folder -> torchvision ImageFolder over class subdirs; etc. A path may be a folder (load all members) or a single file. Build any vocab over train+eval so held-out items never crash encoding. Record dataset provenance in metrics.json (a dataset object: mode, resolved train/test sources, example counts) and report the primary metric on the test split when a test set was supplied.",
    "- Declare how to train your model (so the app tells the user what data to provide): write a static data_contract.json at the workspace ROOT describing YOUR model's data regime -- {\"recommendedMode\": one of builtin|single_corpus|train_test|train_val_test|jsonl_finetune|custom, \"supportedModes\": [..], \"format\": one of text|jsonl|csv|image_folder|other|auto, \"accept\": a file filter like \".txt\" or null, \"builtinFallback\": true|false, \"guidance\": a one-sentence how-to}. The orchestrator surfaces this verbatim in the Experiment panel and it OVERRIDES the scaffold default, so a text LM must declare single_corpus/text (NOT the tabular CSV default). Keep it plain JSON (no code) so it is readable even if torch cannot load. Do NOT edit experiment.json; data_contract.json is the sanctioned channel.",
    "- Training device: pick it from os.environ ACF_DEVICE (one of cpu/cuda/mps), defaulting to cpu when unset, and move both model and batches there; never hard-code cuda. The orchestrator sets ACF_DEVICE to the concrete device it granted (and forces cpu for --smoke), so honoring it is how a run actually uses the GPU.",
    "- CUDA + determinism: torch.use_deterministic_algorithms(True) makes cuBLAS matmuls RAISE on CUDA unless CUBLAS_WORKSPACE_CONFIG is set before the process starts -- the orchestrator already sets it (=:4096:8), so strict determinism does not crash. As defense-in-depth, prefer torch.use_deterministic_algorithms(True, warn_only=True) so any remaining non-deterministic CUDA op (some RNN/scatter kernels) warns instead of killing the whole run.",
    "- Pinning torch for GPU: the orchestrator installs CUDA torch from its configured wheel index (ML_DEFAULT_CUDA_TAG, e.g. cu124), which usually LAGS PyPI's newest release. If you pin torch in requirements.txt, pin a build that index actually publishes (e.g. torch==2.6.0+cu124) or leave torch UNPINNED -- pinning the latest PyPI torch==X (with no +cuNNN local version) makes the CUDA install fail with 'No matching distribution found'. The orchestrator will auto-relax an unavailable pin to the newest build the index offers, but pinning a published build avoids a wasted verification cycle. Also declare numpy explicitly if your code (or torch's numpy bridge) needs it -- torch does not pull it in.",
    "- Keep evaluation efficient: run it in batches (never one example at a time) and bound how often it runs (e.g. eval at the end plus a few checkpoints, scaled to max_steps), so a longer run does not spend all its time in eval.",
    "- Large datasets + the no-output watchdog: the orchestrator stops a run as HUNG after ML_JOB_HEARTBEAT_IDLE_MS of TOTAL silence (no stdout/stderr AND no new metrics.jsonl line); it grants a longer grace only until the FIRST output. So never spend minutes silently loading/encoding before the first metric. (1) BOUND the corpus you read into memory: honor subset_limit and otherwise cap it (e.g. a few tens of MB) and stop reading the file early -- do NOT slurp a multi-GB file in full; a char model over N steps only ever sees ~max_steps*batch*block tokens, so reading the whole corpus is wasted work that can exhaust RAM and trip the watchdog. (2) Encode text into a COMPACT array (numpy uint8/uint16 or a torch tensor), never a Python list of ints (a list of ~1e9 ints needs tens of GB). (3) PRINT a short heartbeat during long data loading/encoding and model/tokenizer downloads so a slow-but-progressing setup is not mistaken for a hang. (4) Read and encode the corpus ONCE (cache vocab/block-size decisions; do not re-read the file per probe).",
    "- metrics.json must carry primary {name,value,split,goal:\"max\"|\"min\"}, a baseline (a real floor: DummyClassifier most_frequent/stratified/uniform, or a random floor), and objectives {wall_s, peak_ram_mb, ...}. Never report a quality number without a baseline to compare against.",
    "- The --smoke path is a fast deterministic wiring gate that exits 0 on success and 1 on failure, checking: import and construct, one forward gives a finite loss, one backward gives finite and nonzero gradients, K steps overfit a tiny fixed batch, a checkpoint saves and reloads to an identical forward, and the same seed reproduces the run (a hard gate on CPU).",
    "- Do NOT mask a broken environment as a passing smoke. If a required dependency (e.g. torch) fails to IMPORT, the smoke must FAIL (exit non-zero) -- never catch the ImportError and write a smoke_report.json with passed:true / \"environment_blocker\". A model whose framework cannot import cannot train or serve, so reporting green hides a non-functional project; let it fail so the orchestrator surfaces the real problem (it independently verifies torch importability and will fail the run anyway).",
    "- Always set and record a seed. For generation/inference tasks, record decode settings (greedy/temperature/top_p/max_new_tokens) and report decode tokens/s; best-of-N is meaningless without fixed decode settings.",
    `- Untrusted weights execute code: prefer safetensors and weights-only loads, and pin a model revision and hash. trust_remote_code is currently ${config.mlTrustRemoteCode ? "ALLOWED (ML_TRUST_REMOTE_CODE=true)" : "DISABLED (ML_TRUST_REMOTE_CODE=false)"}; read os.environ.get("ACF_TRUST_REMOTE_CODE", "0") and pass trust_remote_code=(it == "1") to from_pretrained -- never hard-code trust_remote_code=True.`,
    "- Technique notes: LoRA/QLoRA fine-tuning freezes the base and trains only adapters; quantization reports fidelity (cosine vs fp32) and compression ratio; distillation compares the student against the teacher and a from-scratch student; a Tiny Recursive Model emits per-recursion-depth metrics (a depth field), uses exact-match puzzle eval, and reports seed variance.",
    "- Inference surface (so users can test the trained model with their own inputs): ALSO write predict.py exposing module-level symbols -- CONTRACT (a dict), an optional load() (load the saved checkpoint ONCE and return a handle object), and a predict(...) function returning a dict of outputs. The orchestrator runs predict.py through a bundled harness, so do NOT implement any stdio/JSON protocol yourself; just provide those symbols. Save your trained model under checkpoints/ during the full run and load it in load() (torch: weights_only=True; honor os.environ ACF_DEVICE and ACF_TRUST_REMOTE_CODE). load() should fail fast if no checkpoint exists yet.",
    "- CRITICAL -- how the object load() returns reaches predict(): the harness calls load() ONCE at startup, then for each request calls predict(inputs, options, ctx, handle) IF predict declares a 4th parameter, otherwise predict(inputs, options, ctx). So choose ONE pattern and stick to it: (a) declare the 4th parameter -- def predict(inputs, options, ctx, handle): -- and use handle (exactly what load() returned); or (b) have load() store the model in a MODULE-LEVEL GLOBAL and read that global inside predict (lazy-call load() if it is still unset). The loaded object is ALSO available as ctx.handle in both patterns. NEVER treat ctx as your model -- ctx is the harness context (see the predict() I/O note below), so isinstance(ctx, YourHandle) ALWAYS fails; the model is the 4th arg or ctx.handle, never ctx itself.",
    "- CONTRACT shape: {task, title, inputs:[{name, modality, label, help, required, example?, accept?}], output:{kind, name, unit?, goal?, labels?}, examples:[{label, inputs:{...}}], batch}. modality is one of text|number|image|audio|video|file|tabular|json (the playground renders the matching input widget); output.kind is one of scalar|label|labels|text|image|file|table|json|plot (it renders the matching result view). Provide 1-3 examples so users get one-click test inputs.",
    "- predict() I/O: ctx is the harness CONTEXT object (never your model): ctx.write_file(name, data_bytes, mime) persists an output file and returns a reference to put in the outputs dict, ctx.read_file(ref) resolves a file reference to a local path, ctx.emit_token(text) streams one incremental token to the live playground, and ctx.request_id / ctx.device / ctx.handle (the object load() returned) are available. File inputs (image/audio/video/file modalities) arrive in `inputs[name]` as a ready-to-open local path string; small inputs (text/number/json/tabular) arrive as their literal value. To return a file (e.g. an annotated image), call ctx.write_file(name, data_bytes, mime) and put its return value in the outputs dict. For generation tasks, read decode settings from `options` (temperature/top_p/max_new_tokens/greedy) and return {\"text\": ...}; for regression return {\"<output.name>\": number}; for classification return {\"labels\": [{\"label\": str, \"score\": float}, ...]}. Keep predict() pure and side-effect free so it can run many times on a warm model.",
  ].join("\n");
}
